### ISSUE TITLE
IObservable ToFlowable with Buffer Strategy Never Gives Items and Never Ends

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#39] opened 2022-03-02 15:43 UTC
The following example only ever outputs `OnNext: null` endlessly and never completes:

	var res = await Observable.Repeat("hello", 5)
		.ToFlowable(BackpressureStrategy.BUFFER)
		.DoOnNext(o => Console.WriteLine($"OnNext: {o ?? "null"}"))
		.ToList()
		.FirstTask(CancellationToken.None);

	foreach (var item in res)
	{
		Console.WriteLine($"in list: {item}");
	}

LINQPad script URL: http://share.linqpad.net/648hju.linq

I would have expected this to return "hello" 5 times.

It appears that `ToFlowable(BackPressureStrategy.MISSING).OnBackPressureBuffer()` works correctly.

Using System.Reactive 5.0.0 and Reactive4.NET 0.2.20.

**Comment by akarnokd** [comment] 2022-03-02 15:54
Thanks for reporting. I found the cause and will fix it shortly.

**Comment by akarnokd** [comment] 2022-03-02 16:07
Fixed in 0.2.21.

**Closed as completed by akarnokd** 2022-03-02 16:07 UTC
Labels: bug
